#!/bin/bash

# WPS Spreadsheets wrapper from wps-office-secure

if ! command -v firejail &> /dev/null; then
	logger -is --priority user.warning --tag et "Firejail not found, running et anyway with no sandbox."
	/usr/bin/et
else
	firejail /usr/bin/et "$@"
fi
