#!/bin/bash

# WPS Presentation wrapper from wps-office-secure

if ! command -v firejail &> /dev/null; then
	logger -is --priority user.warning --tag wpp "Firejail not found, running wpp anyway with no sandbox."
	/usr/bin/wpp
else
	firejail /usr/bin/wpp "$@"
fi
